### PR TITLE
native multi token support

### PR DESCRIPTION
**Pull request by SwayStar123**
Currently each contract can only create one native asset. This means that contracts which need NFTS or multiple tokens must awkwardly create their own solutions. This RFC aims to fix that

### CODE REVIEW

**Comment by dmihal** [comment]
Strongly supportive of this, I think multi-asset support would simplify developer experience & let devs fully take adavantage of Fuel's features.

To allow asset IDs to be backwards compatable and remain 32-bytes, we could use the following formula for asset IDs:

```rust
fn asset_id(contract_id: b256, token_id: u64) -> b256 {
  if (token_id == 0) {
    return contract_id;
  } else {
    return sha256(contract_id, token_id);
  }
}
```

**Comment by K1-R1** [comment]
> Strongly supportive of this, I think multi-asset support would simplify developer experience & let devs fully take adavantage of Fuel's features.
> 
> To allow asset IDs to be backwards compatable and remain 32-bytes, we could use the following formula for asset IDs:
> 
> ```rust
> fn asset_id(contract_id: b256, token_id: u64) -> b256 {
>   if (token_id == 0) {
>     return contract_id;
>   } else {
>     return sha256(contract_id, token_id);
>   }
> }
> ```

Might be worth considering having `token_id` be Optional:
 ```sway
 fn asset_id(contract_id: b256, token_id: Option<u64>) -> b256 {
    match token_id {
        Option::None => contract_id,
        Option::Some(token_identifier) => return sha256(contract_id, token_identifier),
 }
 ```

**Comment by K1-R1** [comment]
> The original std::token will change its underlying implementation to always use the 0 token id

Could you be more specific with what this refers to? 
Is this saying that in `std::token` the methods would be replaced to match those in `std::multitoken` but with `token_id` set as 0?

**Comment by SwayStar123** [comment]
> > The original std::token will change its underlying implementation to always use the 0 token id
> 
> Could you be more specific with what this refers to? Is this saying that in `std::token` the methods would be replaced to match those in `std::multitoken` but with `token_id` set as 0?

Yeah, that would give a less verbose api for those who only need one main token.

Im unsure of the method of deriving the assetid via hashing the two, you can go one way with it but not the other way (ie if you have the asset id, theres extra work now to find the contract id that this originates from and its token id).

Is there a problem with just using the original contract id + a token id?

**Comment by K1-R1** [comment]
> Is there a problem with just using the original contract id + a token id?

Is there any potential that this could result in an scenario where one contract's `contract id + a token id` would be the same as some other contract' s `contract_id`?

**Comment by dmihal** [comment]
> Is there a problem with just using the original contract id + a token id?

Potential attack vector, if there's two contracts whose addresses are less than 2^64 apart, then the first contract can create an asset that collides with the second contract. Easier to just hash them

> Im unsure of the method of deriving the assetid via hashing the two, you can go one way with it but not the other way (ie if you have the asset id, theres extra work now to find the contract id that this originates from and its token id).

Hmm maybe we can have the VM track it, and have a precompile that maps AssetIds back to their issuer

**Comment by dmihal** [comment]
Proposed VM changes are here:
https://github.com/FuelLabs/fuel-specs/pull/491

**Comment by SwayStar123** [comment]
Created an issue https://github.com/FuelLabs/rfcs/issues/18 and linked it

**Comment by bitzoic** [comment]
Closing in favor of https://github.com/FuelLabs/fuel-specs/pull/491

**Pull request closed without merging**
